### ISSUE TITLE
Support to collection types of OrientDB

### ISSUE THREAD

**Issue by schernolyas** [RedfieldAB/KnimeOrientDB#5]
It is needs support to collection types of  OrientDB .
See details at https://orientdb.com/docs/last/Types.html

**Comment by schernolyas** [comment]
Caused by: java.lang.UnsupportedOperationException: Unsupported cell type List (Collection of: Number (integer)) (class : org.knime.core.data.collection.ListCell) !
	at se.redfield.node.port.orientdb.command.OrientDBCommandNodeModel.saveDataRow(OrientDBCommandNodeModel.java:462)
	at se.redfield.node.port.orientdb.command.OrientDBCommandNodeModel.access$2(OrientDBCommandNodeModel.java:404)
	at se.redfield.node.port.orientdb.command.OrientDBCommandNodeModel$2$1.call(OrientDBCommandNodeModel.java:305)
	at se.redfield.node.port.orientdb.command.OrientDBCommandNodeModel$2$1.call(OrientDBCommandNodeModel.java:1)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
